# Generated by Django 4.2.7 on 2023-11-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
