# Generated by Django 4.2.7 on 2023-11-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0002_alter_company_name_alter_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transport",
            name="driver",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transport",
            name="license_plate",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
